### ISSUE TITLE
Improve style, layout or responsivity.

### ISSUE THREAD

**Issue by MaurerKrisztian** [MaurerKrisztian/FilterCreator#2]
Improve the FilterCreator ui style, layout or responsivity.

**Comment by RaviAnand111** [comment]
I can do it. Can you guys elaborate what have to be done ?

**Comment by MaurerKrisztian** [comment]
Hi!  I'm glad you're interested.  I'm open to ideas but I thought of something like this:

![basic_online_photo_editor.jpg](https://user-images.githubusercontent.com/48491140/132920450-c971329b-ee0f-4eb8-be07-cd348bf7ebc9.jpg)
- similar layout as in the picture above
- if no image is loaded, a "choose image" button should be displayed in place of the image
- the "set changes, reset, show histogram, download" buttons appear in the top menu shown in the image above
- the layout and image size should be responsive

You don’t have to do everything in one step. If you have any other ideas you can bring it in. Have fun! 😃

**Comment by RaviAnand111** [comment]
I can do the frontend part like css but not backend like what happens on clicking specific button ? will that work for you ?

**Comment by MaurerKrisztian** [comment]
Yes that's okay, just be careful not to change the slider, button ids because the backend refers to them

**Comment by TejasSathe010** [comment]
I see the issue is open, I am ready to contribute and resolve the issue. Please let me if so. @RaviAnand111 Please push your changes if you've done anything.

**Comment by RaviAnand111** [comment]
I was busy in some stuff, you can go ahead
